In [1]:
pip install torch

  Using cached torch-2.2.2-cp312-none-macosx_10_9_x86_64.whl.metadata (25 kB)
  Using cached filelock-3.17.0-py3-none-any.whl.metadata (2.9 kB)
  Using cached sympy-1.13.3-py3-none-any.whl.metadata (12 kB)
  Using cached networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
  Using cached fsspec-2025.2.0-py3-none-any.whl.metadata (11 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Using cached torch-2.2.2-cp312-none-macosx_10_9_x86_64.whl (150.8 MB)
Using cached filelock-3.17.0-py3-none-any.whl (16 kB)
Using cached fsspec-2025.2.0-py3-none-any.whl (184 kB)
Using cached networkx-3.4.2-py3-none-any.whl (1.7 MB)
Using cached sympy-1.13.3-py3-none-any.whl (6.2 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Note: you may need to restart th

In [1]:
import torch
import torch.nn.functional as F

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/torch/nn/modules/transformer.py:20: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  device: torch.device = torch.device(torch._C._get_default_device()),  # torch.device('cpu'),


In [2]:
words = open("./names.txt").read().splitlines()
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [3]:
len(words)

32033

In [4]:
for i, w in enumerate(words):
    words[i] = '.' + w
words[:10]

['.emma',
 '.olivia',
 '.ava',
 '.isabella',
 '.sophia',
 '.charlotte',
 '.mia',
 '.amelia',
 '.harper',
 '.evelyn']

In [6]:
chs = []
for w in words:
    chs += list(w)
chs[:10]

['.', 'e', 'm', 'm', 'a', '.', 'o', 'l', 'i', 'v']

In [7]:
lookup_values = sorted(set(chs))

In [8]:
stoi = {lookup_value : i for i, lookup_value in enumerate(lookup_values)}
itos = {i : lookup_value for i, lookup_value in enumerate(lookup_values)}
stoi

{'.': 0,
 'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26}

In [33]:
itos

{0: '.',
 1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z'}

In [9]:
for i, ch in enumerate(chs):
    chs[i] = stoi[ch]
chs[:10]

[0, 5, 13, 13, 1, 0, 15, 12, 9, 22]

In [10]:
x = torch.tensor(chs[:len(chs)-1], dtype = torch.int64)
x[:10]

tensor([ 0,  5, 13, 13,  1,  0, 15, 12,  9, 22])

In [13]:
x.shape

torch.Size([228145])

In [11]:
y = torch.tensor(chs[1:], dtype = torch.int64)
y[:10]

tensor([ 5, 13, 13,  1,  0, 15, 12,  9, 22,  9])

In [12]:
y.shape

torch.Size([228145])

In [14]:
xenc = F.one_hot(x, num_classes = 27).float()
xenc

tensor([[1., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 1., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

In [15]:
xenc.dtype

torch.float32

In [16]:
xenc.shape

torch.Size([228145, 27])

In [17]:
g = torch.Generator().manual_seed(2147483647)
w = torch.randn((27, 27), dtype = torch.float32, requires_grad = True, generator = g)
w

tensor([[ 1.5674e+00, -2.3729e-01, -2.7385e-02, -1.1008e+00,  2.8588e-01,
         -2.9643e-02, -1.5471e+00,  6.0489e-01,  7.9136e-02,  9.0462e-01,
         -4.7125e-01,  7.8682e-01, -3.2843e-01, -4.3297e-01,  1.3729e+00,
          2.9334e+00,  1.5618e+00, -1.6261e+00,  6.7716e-01, -8.4039e-01,
          9.8488e-01, -1.4837e-01, -1.4795e+00,  4.4830e-01, -7.0730e-02,
          2.4968e+00,  2.4448e+00],
        [-6.7006e-01, -1.2199e+00,  3.0314e-01, -1.0725e+00,  7.2762e-01,
          5.1114e-02,  1.3095e+00, -8.0220e-01, -8.5042e-01, -1.8068e+00,
          1.2523e+00, -1.2256e+00,  1.2165e+00, -9.6478e-01, -2.3211e-01,
         -3.4762e-01,  3.3244e-01, -1.3263e+00,  1.1224e+00,  5.9641e-01,
          4.5846e-01,  5.4011e-02, -1.7400e+00,  1.1560e-01,  8.0319e-01,
          5.4108e-01, -1.1646e+00],
        [ 1.4756e-01, -1.0006e+00,  3.8012e-01,  4.7328e-01, -9.1027e-01,
         -7.8305e-01,  1.3506e-01, -2.1161e-01, -1.0406e+00, -1.5367e+00,
          9.3743e-01, -8.8303e-01,  1.74

In [32]:
#Forward pass
for i in range(100):
    logits = xenc @ w
    softmax = F.softmax(logits, dim = -1)
    target_probs = softmax[torch.arange(228145), y]
    loss = -(target_probs).log().mean() + 0.01 * (w**2).mean()
    if i%10 == 0:
        print(loss)
    w.grad = None
    loss.backward()
    w.data += (-100 * w.grad)

tensor(2.4817, grad_fn=<AddBackward0>)
tensor(2.4815, grad_fn=<AddBackward0>)
tensor(2.4814, grad_fn=<AddBackward0>)
tensor(2.4892, grad_fn=<AddBackward0>)
tensor(2.5021, grad_fn=<AddBackward0>)
tensor(2.4982, grad_fn=<AddBackward0>)
tensor(2.5017, grad_fn=<AddBackward0>)
tensor(2.4981, grad_fn=<AddBackward0>)
tensor(2.5018, grad_fn=<AddBackward0>)
tensor(2.5011, grad_fn=<AddBackward0>)


In [139]:
#inference
g = torch.Generator().manual_seed(2147483647)
def forward(i, name):
    i = torch.tensor([stoi[i]], dtype = torch.int64)
    ienc = F.one_hot(i, num_classes = 27).float()
    logits = ienc @ w
    softmax = F.softmax(logits, dim = -1)
    predicted = torch.multinomial(softmax, num_samples = 1, replacement = True, generator = g)
    predicted = itos[predicted.item()]
    name += predicted
    if predicted == '.':
        print(name)
        return
    forward(predicted, name)

for i in range(5):
    i = '.'
    forward(i, "")

junide.
ja.
asah.
p.
cfay.
